// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradesUIClient is the client API for TradesUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradesUIClient interface {
	// ListEngineSpecs returns a list of Trading Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TradesUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type tradesUIClient struct {
	cc grpc.ClientConnInterface
}

func NewTradesUIClient(cc grpc.ClientConnInterface) TradesUIClient {
	return &tradesUIClient{cc}
}

func (c *tradesUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TradesUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TradesUI_ServiceDesc.Streams[0], "/v1.TradesUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradesUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TradesUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type tradesUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *tradesUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tradesUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.TradesUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradesUIServer is the server API for TradesUI service.
// All implementations must embed UnimplementedTradesUIServer
// for forward compatibility
type TradesUIServer interface {
	// ListEngineSpecs returns a list of Trading Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, TradesUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedTradesUIServer()
}

// UnimplementedTradesUIServer must be embedded to have forward compatible implementations.
type UnimplementedTradesUIServer struct {
}

func (UnimplementedTradesUIServer) ListEngineSpecs(*ListEngineSpecsRequest, TradesUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedTradesUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedTradesUIServer) mustEmbedUnimplementedTradesUIServer() {}

// UnsafeTradesUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradesUIServer will
// result in compilation errors.
type UnsafeTradesUIServer interface {
	mustEmbedUnimplementedTradesUIServer()
}

func RegisterTradesUIServer(s grpc.ServiceRegistrar, srv TradesUIServer) {
	s.RegisterService(&TradesUI_ServiceDesc, srv)
}

func _TradesUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradesUIServer).ListEngineSpecs(m, &tradesUIListEngineSpecsServer{stream})
}

type TradesUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type tradesUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *tradesUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TradesUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradesUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TradesUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradesUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradesUI_ServiceDesc is the grpc.ServiceDesc for TradesUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradesUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TradesUI",
	HandlerType: (*TradesUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _TradesUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _TradesUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trades-ui.proto",
}
